### ISSUE TITLE
您好，请问fewshot训练的时候加不加--use_sampled_data结果没有区别吧？只是简化训练过程了是嘛

### ISSUE THREAD

**Issue by KAYY123** [thunlp/Few-NERD#30]

**Comment by cyl628** [comment]
Hi, adding `--use_sampled_data` will train on the sampled data (can be downloaded here https://cloud.tsinghua.edu.cn/f/0e38bd108d7b49808cc4/?dl=1). Otherwise, it will be sampling episodes out of the data pool while training. There may be difference between the two due to sampling randomness. The result reported in our paper uses the pre-sampled data.
