### ISSUE TITLE
Why this dataset use IO scheme?

### ISSUE THREAD

**Issue by yananchen1989** [thunlp/Few-NERD#36]
Hi, I am just curious why this dataset use IO scheme tagging, instead of using BIO etc...

Can you authors elaborate why ?

Thanks in advance.

**Comment by cyl628** [comment]
Hi, sorry for the late reply. I personally think using BIO or other schemes will also be fine. Using IO scheme is more due to a simplicity consideration (so that tokens are only to be decided if they are part of entity mention or not).
Using BIO scheme means there are more labels and the label distribution may vary more when performing few-shot sampling. So it may require more consideration and analysis in terms of data sampling. We didn't really do experiment on that, maybe you can try that.
